[
    ["FUNGAL_SHIFT", "你听见“?”这个词在回响，变换着色彩", "fungal_shift"],
    ["BOOBY_TRAPPED", "这里陷阱遍布", "booby_trapped"],
    ["CONDUCTIVE", "空气像是被电离了", "conductive"],
    ["FOG_OF_WAR_REAPPEARS", "神秘的黑暗笼罩在这里", "fog_of_war"],
    ["FOG_OF_WAR_CLEAR_AT_PLAYER", "这里非常昏暗", "fog_of_war_clear_at_player"],
    ["FREEZING", "空气寒冷刺骨", "freezing"],
    ["FUNGAL", "空气中弥漫着孢子", "fungal"],
    ["FURNISHED", "这里让你感觉很舒适", "furnished"],
    ["GAS_FLOODED", "空气中有燃气的味道", "gas"],
    ["GOLD_VEIN", "你感觉这里埋藏着财富", "gold"],
    ["GOLD_VEIN_SUPER", "你感觉这里埋藏着巨大的财富", "gold"],
    ["GRAVITY_FIELDS", "你感到一股无形的力量在拉扯着你", "gravity_fields"],
    ["HIGH_GRAVITY", "空气很是沉重", "high_gravity"],
    ["HOT", "一股热浪扑面而来", "hot"],
    ["INVISIBILITY", "你突然无法聚焦视线", "invisible"],
    ["LOW_GRAVITY", "空气很是轻盈", "low_gravity"],
    ["FLOODED", "这些水是从哪里来的？", "moist"],
    ["OMINOUS", "一切都感觉要被黑暗吞噬", "ominous"],
    ["PERFORATED", "这里感觉很宽敞", "perforated"],
    ["PLANT_INFESTED", "闻起来好像雨后泥土的气味", "plant_infested"],
    ["SHIELDED", "这里真是太安全了", "shielded"],
    ["SPOOKY", "你的后背发凉，汗毛直竖", "spooky"],
    ["PROTECTION_FIELDS", "一切都沐浴在神秘的光芒之中", "sunlight"],
    ["WORMY", "可怕的爬动声到处都是", "wormy"]
];
