//prettier-ignore
[
    ["spellType", new this(1, "法术类型")],
    ["materialType", new this(1, "材料类型")], //材料属性
    ["shuffle", new this(2, "乱序", "shuffle")],
    ["draw", new this(3, "抽取数", "draw")],
    ["capacity", new this(4, "容量", "capacity")],
    ["staticSpells", new this(5, "始终施放")],
    ["manaMax", new this(6, "法力上限", "mana-max")],
    ["manaChargeSpeed", new this(7, "法力恢复速度", "mana-charge-speed")],
    ["manaDrain", new this(8, "法力消耗")],
    ["maxUse", new this(9, "最大使用次数")],
    ["remainingUse", new this(9, "剩余使用次数")],
    ["fireRateWait", new this(10, "施放延迟", "fire-rate-wait")],
    ["reloadTime", new this(11, "充能时间", "reload-time")],
    ["spreadDegrees", new this(12, "散射", "spread-degrees")],
    ["projectileDamage", new this(13, "投射物伤害")],
    ["projectileDamageMultiplier", new this(13, "投射物承伤")],
    ["fireDamage", new this(14, "火焰伤害")],
    ["fireDamageMultiplier", new this(14, "火焰承伤")],
    ["iceDamage", new this(15, "冰冻伤害")],
    ["iceDamageMultiplier", new this(15, "冰冻承伤")],
    ["explosionDamage", new this(16, "爆炸伤害")],
    ["explosionDamageMultiplier", new this(16, "爆炸承伤")],
    ["sliceDamage", new this(17, "切割伤害")],
    ["sliceDamageMultiplier", new this(17, "切割承伤")],
    ["drillDamage", new this(18, "穿凿伤害")],
    ["drillDamageMultiplier", new this(18, "穿凿承伤")],
    ["durability", new this(18, "硬度")], //材料属性
    ["electricityDamage", new this(19, "雷电伤害")],
    ["electricityDamageMultiplier", new this(19, "雷电承伤")],
    ["conductivity", new this(19, "导电性")], //材料属性
    ["healingDamage", new this(20, "治疗伤害")],
    ["healingDamageMultiplier", new this(20, "治疗承伤")],
    ["meleeDamage", new this(21, "近战伤害")],
    ["meleeDamageMultiplier", new this(21, "近战承伤")],
    ["curseDamage", new this(22, "诅咒伤害")],
    ["curseDamageMultiplier", new this(22, "诅咒承伤")],
    ["holyDamage", new this(23, "神圣伤害")],
    ["holyDamageMultiplier", new this(23, "神圣承伤")],
    ["overeatingDamage", new this(24, "吃撑伤害")],
    ["overeatingDamageMultiplier", new this(24, "吃撑承伤")],
    ["ingestionStatusEffects", new this(24, "摄入效果")], //材料属性
    ["physicsHitDamage", new this(25, "物理伤害")],
    ["physicsHitDamageMultiplier", new this(25, "物理承伤")],
    ["poisonDamage", new this(26, "剧毒伤害")],
    ["poisonDamageMultiplier", new this(26, "剧毒承伤")],
    ["stainsStatusEffects", new this(26, "沾染效果")], //材料属性
    ["radioactiveDamage", new this(27, "辐射伤害")],
    ["radioactiveDamageMultiplier", new this(27, "辐射承伤")],
    ["damageCriticalChance", new this(28, "暴击率")],
    ["speed", new this(29, "投射速度")],
    ["speedMultiplier", new this(29, "投射速度倍数")],
    ["explosionRadius", new this(30, "爆炸半径")],
    ["bounces", new this(31, "弹起次数")],
    ["knockbackForce", new this(32, "击退")],
    ["lifetime", new this(33, "存在时间")],
    ["projectilesProvided", new this(34, "提供投射物")],
    ["projectilesRelated", new this(34, "关联投射物")],
    ["projectilesUsed", new this(34, "使用投射物")],
    ["passiveEffect", new this(35, "被动效果")],
    ["bloodMaterial", new this(36, "血液材料")],
    ["friendlyFire", new this(36, "友方命中")],
    ["maxHp", new this(37, "生命值")],
    ["immunity", new this(38, "免疫能力")],
    ["#1", new this(39, "#1")], /// 未启用图标
    ["recoil", new this(40, "后座力")],
    ["draw_common", new this(41, "抽取|普通")],
    ["draw_hit", new this(42, "碰撞触发")],
    ["draw_timer", new this(43, "定时触发")],
    ["draw_death", new this(44, "失效触发")],
    ["#2", new this(45, "#2")], /// 未启用图标
    ["camp", new this(46, "阵营")],
    ["maxStack", new this(47, "堆叠极限")],
    ["maxInPool", new this(48, "池最大含量")],
    ["airInLungsMax", new this(49, "肺容量")],
    ["patternDegrees", new this(50, "阵型分布")],
    ["trailMaterial", new this(51, "提供轨迹")],
    ["trailMaterialAmount", new this(52, "轨迹浓度")],
    ["material", new this(53, "提供材料")],
    ["materialAmount", new this(54, "材料浓度")],
    ["temperature", new this(55, "自燃温度")],
    ["lock", new this(56, "生成锁")],
    ["unlock", new this(57, "解锁条件")],
    ["#3", new this(58, "#3")], /// 未启用图标
    ["#4", new this(59, "#镐子")], /// 未启用图标
    ["#5", new this(60, "#铲子")], /// 未启用图标
    ["#6", new this(61, "#锤子")], /// 未启用图标
    ["#9", new this(62, "#扳手")], /// 未启用图标
    ["#10", new this(63, "#双刃斧")], /// 未启用图标
    ["#11", new this(64, "#图钉")], /// 未启用图标
    ["wand", new this(65, "魔杖")], /// 未启用图标
    ["orbitProjectile", new this(66, "环绕投射物")],//未启用图标
    ["probs", new this(67, "生成概率")],
    ["action", new this(68, "法术行为")],
    ["action_", new this(69, "法术行为_")],
    ["menu", new this(70, "菜单")],
    ["box", new this(71, "盒子")],
    ["#12", new this(72, "??")],
    ["filter", new this(73, "过滤器")],
    ["gnaw", new this(74, "啃咬")],
    ["chip1", new this(75, "芯片1")],
    ["chip2", new this(76, "芯片2")],
    ["stack", new this(77, "栈")],
    ["#13", new this(78, "??")],
    ["#14", new this(79, "??")],
    ["#15", new this(80, "??")],
    ["#16", new this(81, "??")]
]
